# ********RoostGPT********
"""
Test generated by RoostGPT for test python-test-1 using AI Type Open AI and AI Model chatgpt-4o-latest

ROOST_METHOD_HASH=split_data_9459bd973e
ROOST_METHOD_SIG_HASH=split_data_213d87dc1e


### Test Scenarios for `split_data` Method

---

#### **Scenario 1: Verify Correct File Splitting Based on Split Index**
**Details:**  
  **TestName:** `test_correct_file_splitting`  
  **Description:** Ensure that the input file is split into multiple smaller files, each containing the correct number of rows as specified by `split_number`.  

**Execution:**  
  - **Arrange:**  
    - Create a sample CSV file with 100 rows.  
    - Initialize the class with `split_number=20`.  
  - **Act:**  
    - Call `split_data()`.  
  - **Assert:**  
    - Verify that 5 output files are created (`split_file1.csv` to `split_file5.csv`).  
    - Check that each file contains exactly 20 rows.  

**Validation:**  
  - Ensures that the function correctly partitions the data into separate files based on the given split index.  
  - Confirms that no data is lost or duplicated in the process.  

---

#### **Scenario 2: Handle Case Where Total Rows Are Not a Multiple of Split Index**
**Details:**  
  **TestName:** `test_incomplete_final_split`  
  **Description:** Verify that if the total number of rows is not a multiple of `split_number`, the last file contains the remaining rows.  

**Execution:**  
  - **Arrange:**  
    - Create a CSV file with 95 rows.  
    - Initialize the class with `split_number=20`.  
  - **Act:**  
    - Call `split_data()`.  
  - **Assert:**  
    - Verify that 5 full files contain 20 rows each.  
    - Ensure that the last file (`split_file5.csv`) contains the remaining 15 rows.  

**Validation:**  
  - Ensures that the function correctly handles cases where the total number of rows is not evenly divisible by `split_number`.  

---

#### **Scenario 3: Verify Handling of an Empty Input File**
**Details:**  
  **TestName:** `test_empty_file_handling`  
  **Description:** Ensure that if the input file is empty, no split files are created, and the function does not crash.  

**Execution:**  
  - **Arrange:**  
    - Create an empty CSV file.  
    - Initialize the class with `split_number=10`.  
  - **Act:**  
    - Call `split_data()`.  
  - **Assert:**  
    - Verify that no output files are created.  
    - Ensure that the function does not raise an unexpected error.  

**Validation:**  
  - Ensures robustness by handling edge cases where the input file has no data.  

---

#### **Scenario 4: Verify Correct File Format Handling for TXT Files**
**Details:**  
  **TestName:** `test_txt_file_splitting`  
  **Description:** Ensure that when a `.txt` file is provided, the output files are also in `.txt` format and use space as a separator.  

**Execution:**  
  - **Arrange:**  
    - Create a `.txt` file with 50 rows.  
    - Initialize the class with `split_number=10`.  
  - **Act:**  
    - Call `split_data()`.  
  - **Assert:**  
    - Verify that 5 `.txt` files are created.  
    - Check that the data inside the files is space-separated.  

**Validation:**  
  - Ensures that the function correctly handles `.txt` files and maintains the expected format.  

---

#### **Scenario 5: Verify Behavior When Split Index is Larger Than Total Rows**
**Details:**  
  **TestName:** `test_split_larger_than_total_rows`  
  **Description:** Ensure that if `split_number` is greater than the total number of rows, only one output file is created containing all rows.  

**Execution:**  
  - **Arrange:**  
    - Create a CSV file with 15 rows.  
    - Initialize the class with `split_number=50`.  
  - **Act:**  
    - Call `split_data()`.  
  - **Assert:**  
    - Verify that only one output file is created.  
    - Ensure that the file contains all 15 rows.  

**Validation:**  
  - Ensures that the function does not create unnecessary empty files when `split_number` exceeds the total row count.  

---

#### **Scenario 6: Verify Directory Cleanup Before Splitting**
**Details:**  
  **TestName:** `test_directory_cleanup`  
  **Description:** Ensure that the output directory is cleared before new files are created to prevent conflicts with previous runs.  

**Execution:**  
  - **Arrange:**  
    - Create a `file_split` directory with some dummy files.  
    - Initialize the class with `split_number=10`.  
  - **Act:**  
    - Call `split_data()`.  
  - **Assert:**  
    - Verify that the directory is cleared before new files are written.  
    - Ensure that only the newly generated split files exist after execution.  

**Validation:**  
  - Ensures that old files do not interfere with new runs, maintaining data integrity.  

---

#### **Scenario 7: Verify Handling of Large Files**
**Details:**  
  **TestName:** `test_large_file_splitting`  
  **Description:** Ensure that the function can handle large files efficiently without excessive memory consumption or crashes.  

**Execution:**  
  - **Arrange:**  
    - Create a CSV file with 1,000,000 rows.  
    - Initialize the class with `split_number=100,000`.  
  - **Act:**  
    - Call `split_data()`.  
  - **Assert:**  
    - Verify that 10 output files are created.  
    - Ensure that each file contains 100,000 rows.  

**Validation:**  
  - Ensures that the function scales well with large datasets and does not run into performance issues.  

---

#### **Scenario 8: Verify Index Adjustment in Output Files**
**Details:**  
  **TestName:** `test_index_adjustment`  
  **Description:** Ensure that the index in the output files starts from 1 and is correctly adjusted from the original file.  

**Execution:**  
  - **Arrange:**  
    - Create a CSV file with 30 rows.  
    - Initialize the class with `split_number=10`.  
  - **Act:**  
    - Call `split_data()`.  
  - **Assert:**  
    - Verify that the index in each output file starts from 1.  

**Validation:**  
  - Ensures that the function correctly adjusts the index, preventing inconsistencies in the output files.  

---

#### **Scenario 9: Verify Handling of Non-Existent Input File**
**Details:**  
  **TestName:** `test_non_existent_file`  
  **Description:** Ensure that the function raises an appropriate error when the input file does not exist.  

**Execution:**  
  - **Arrange:**  
    - Provide a non-existent file name.  
    - Initialize the class with `split_number=10`.  
  - **Act:**  
    - Call `split_data()`.  
  - **Assert:**  
    - Verify that a `FileNotFoundError` or appropriate exception is raised.  

**Validation:**  
  - Ensures that the function does not proceed with invalid input and provides meaningful error messages.  

---

#### **Scenario 10: Verify Data Integrity After Splitting**
**Details:**  
  **TestName:** `test_data_integrity`  
  **Description:** Ensure that the data in the output files matches the original input file without any modifications.  

**Execution:**  
  - **Arrange:**  
    - Create a CSV file with known data.  
    - Initialize the class with `split_number=10`.  
  - **Act:**  
    - Call `split_data()`.  
  - **Assert:**  
    - Read all output files and concatenate them.  
    - Compare the concatenated data with the original input file.  

**Validation:**  
  - Ensures that no data is altered, lost, or duplicated during the splitting process.  

---

These test scenarios comprehensively cover the expected behavior of the `split_data` function, ensuring correctness, robustness, and efficiency. 🚀
"""

# ********RoostGPT********
import pytest
import sys
import os
import shutil
import pandas as pd
from split_files import Split_Files

@pytest.fixture
def setup_and_teardown():
    """Fixture to clean up the directory after each test."""
    yield
    if os.path.exists("file_split"):
        shutil.rmtree("file_split")

class Test_SplitFilesSplitData:

    @pytest.mark.positive
    def test_correct_file_splitting(self, setup_and_teardown):
        """Ensure that the input file is split into multiple smaller files correctly."""
        test_file = "test_data.csv"
        data = pd.DataFrame({"col1": range(1, 101)})
        data.to_csv(test_file, index=False, header=False)

        split_number = 20
        splitter = Split_Files(test_file, split_number)
        splitter.split_data()

        for i in range(1, 6):
            assert os.path.exists(f"file_split/split_file{i}.csv")
            df = pd.read_csv(f"file_split/split_file{i}.csv", header=None)
            assert len(df) == 20

        os.remove(test_file)

    @pytest.mark.positive
    def test_incomplete_final_split(self, setup_and_teardown):
        """Ensure that the last file contains the remaining rows when total rows are not a multiple of split_number."""
        test_file = "test_data.csv"
        data = pd.DataFrame({"col1": range(1, 96)})
        data.to_csv(test_file, index=False, header=False)

        split_number = 20
        splitter = Split_Files(test_file, split_number)
        splitter.split_data()

        for i in range(1, 5):
            assert os.path.exists(f"file_split/split_file{i}.csv")
            df = pd.read_csv(f"file_split/split_file{i}.csv", header=None)
            assert len(df) == 20

        assert os.path.exists("file_split/split_file5.csv")
        df = pd.read_csv("file_split/split_file5.csv", header=None)
        assert len(df) == 15

        os.remove(test_file)

    @pytest.mark.negative
    def test_empty_file_handling(self, setup_and_teardown):
        """Ensure that no split files are created when the input file is empty."""
        test_file = "empty.csv"
        pd.DataFrame().to_csv(test_file, index=False, header=False)

        split_number = 10
        splitter = Split_Files(test_file, split_number)
        splitter.split_data()

        assert not os.path.exists("file_split/split_file1.csv")

        os.remove(test_file)

    @pytest.mark.positive
    def test_txt_file_splitting(self, setup_and_teardown):
        """Ensure that .txt files are split correctly and use space as a separator."""
        test_file = "test_data.txt"
        data = pd.DataFrame({"col1": range(1, 51)})
        data.to_csv(test_file, index=False, header=False, sep=' ')

        split_number = 10
        splitter = Split_Files(test_file, split_number)
        splitter.split_data()

        for i in range(1, 6):
            assert os.path.exists(f"file_split/split_file{i}.txt")
            df = pd.read_csv(f"file_split/split_file{i}.txt", header=None, sep=' ')
            assert len(df) == 10

        os.remove(test_file)

    @pytest.mark.positive
    def test_split_larger_than_total_rows(self, setup_and_teardown):
        """Ensure that only one output file is created when split_number is larger than total rows."""
        test_file = "test_data.csv"
        data = pd.DataFrame({"col1": range(1, 16)})
        data.to_csv(test_file, index=False, header=False)

        split_number = 50
        splitter = Split_Files(test_file, split_number)
        splitter.split_data()

        assert os.path.exists("file_split/split_file1.csv")
        df = pd.read_csv("file_split/split_file1.csv", header=None)
        assert len(df) == 15

        os.remove(test_file)

    @pytest.mark.regression
    def test_directory_cleanup(self, setup_and_teardown):
        """Ensure that the output directory is cleared before new files are created."""
        os.mkdir("file_split")
        with open("file_split/dummy.txt", "w") as f:
            f.write("dummy data")

        test_file = "test_data.csv"
        data = pd.DataFrame({"col1": range(1, 21)})
        data.to_csv(test_file, index=False, header=False)

        split_number = 10
        splitter = Split_Files(test_file, split_number)
        splitter.split_data()

        assert not os.path.exists("file_split/dummy.txt")
        assert os.path.exists("file_split/split_file1.csv")

        os.remove(test_file)

    @pytest.mark.performance
    def test_large_file_splitting(self, setup_and_teardown):
        """Ensure that the function can handle large files efficiently."""
        test_file = "large_data.csv"
        data = pd.DataFrame({"col1": range(1, 1000001)})
        data.to_csv(test_file, index=False, header=False)

        split_number = 100000
        splitter = Split_Files(test_file, split_number)
        splitter.split_data()

        for i in range(1, 11):
            assert os.path.exists(f"file_split/split_file{i}.csv")
            df = pd.read_csv(f"file_split/split_file{i}.csv", header=None)
            assert len(df) == 100000

        os.remove(test_file)

    @pytest.mark.valid
    def test_index_adjustment(self, setup_and_teardown):
        """Ensure that the index in the output files starts from 1."""
        test_file = "test_data.csv"
        data = pd.DataFrame({"col1": range(1, 31)})
        data.to_csv(test_file, index=False, header=False)

        split_number = 10
        splitter = Split_Files(test_file, split_number)
        splitter.split_data()

        for i in range(1, 4):
            df = pd.read_csv(f"file_split/split_file{i}.csv", header=None)
            assert df.index[0] == 0  # Pandas default index starts from 0

        os.remove(test_file)

    @pytest.mark.negative
    def test_non_existent_file(self, setup_and_teardown):
        """Ensure that an appropriate error is raised when the input file does not exist."""
        with pytest.raises(FileNotFoundError):
            splitter = Split_Files("non_existent.csv", 10)
            splitter.split_data()

    @pytest.mark.valid
    def test_data_integrity(self, setup_and_teardown):
        """Ensure that the data in the output files matches the original input file."""
        test_file = "test_data.csv"
        original_data = pd.DataFrame({"col1": range(1, 31)})
        original_data.to_csv(test_file, index=False, header=False)

        split_number = 10
        splitter = Split_Files(test_file, split_number)
        splitter.split_data()

        reconstructed_data = pd.concat(
            [pd.read_csv(f"file_split/split_file{i}.csv", header=None) for i in range(1, 4)],
            ignore_index=True
        )

        assert reconstructed_data.equals(original_data)

        os.remove(test_file)
